# Generated by Django 4.1.7 on 2023-03-20 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='xarajatlar',
            name='comment',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
    ]
