# Generated by Django 3.2.9 on 2023-03-27 06:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homes', '0004_auto_20230321_1946'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='xarajatlar',
            name='date',
        ),
    ]
