# Generated by Django 3.2.9 on 2023-03-27 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homes', '0005_remove_xarajatlar_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='xarajatlar',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
