# Generated by Django 3.2.9 on 2023-03-27 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homes', '0007_hodim_ishxaqixarajati'),
    ]

    operations = [
        migrations.AddField(
            model_name='ishxaqixarajati',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
